### ISSUE TITLE
Sweep: Dynamic server usage: Page couldn't be rendered statically because it used `headers`.

### ISSUE THREAD

**Issue by mikepsinn** [wishonia/wishonia#50]
### Details
The below error is coming from this file, I guess:
`/app/api/globalSolutionPairAllocation/random/route.ts`

[Error]: Dynamic server usage: Page couldn't be rendered statically because it used `headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
    at l (/vercel/path0/.next/server/chunks/1769.js:63:7515)
    at p (/vercel/path0/.next/server/chunks/1769.js:63:4603)
    at s (/vercel/path0/.next/server/chunks/1769.js:30:19045)
    at o (/vercel/path0/.next/server/app/api/globalProblemPairAllocation/random/route.js:1:2450)
    at d (/vercel/path0/.next/server/app/api/globalSolutionPairAllocation/random/route.js:18:244)
    at /vercel/path0/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.7_supports-color@8.1.1__babel-plugin-macros@3.1.0_react-dom@18.2_xvifaqpqufhcthoaz4ndbpccii/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42490
    at /vercel/path0/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.7_supports-color@8.1.1__babel-plugin-macros@3.1.0_react-dom@18.2_xvifaqpqufhcthoaz4ndbpccii/node_modules/next/dist/server/lib/trace/tracer.js:133:36
    at NoopContextManager.with (/vercel/path0/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.7_supports-color@8.1.1__babel-plugin-macros@3.1.0_react-dom@18.2_xvifaqpqufhcthoaz4ndbpccii/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/vercel/path0/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.7_supports-color@8.1.1__babel-plugin-macros@3.1.0_react-dom@18.2_xvifaqpqufhcthoaz4ndbpccii/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/vercel/path0/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.7_supports-color@8.1.1__babel-plugin-macros@3.1.0_react-dom@18.2_xvifaqpqufhcthoaz4ndbpccii/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093) {

**Comment by mikepsinn** [comment]
This is the file /app/api/globalSolutionPairAllocation/random/route.ts
